import { useClimate } from '@/context/ClimateContext';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, DropdownMenuSeparator, DropdownMenuLabel } from '@/components/ui/dropdown-menu';
import { Download, FileJson, FileSpreadsheet, FileText, Check } from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';

export const SmartExport = () => {
  const { exportCurrentState, selectedScenario, selectedScope, scenarios } = useClimate();

  const exportData = exportCurrentState();

  const downloadJSON = () => {
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `climate-report-${selectedScenario}-${format(new Date(), 'yyyy-MM-dd')}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report exported as JSON', {
      description: `${scenarios[selectedScenario].name} scenario with ${selectedScope} scope filter`,
    });
  };

  const downloadCSV = () => {
    const rows = [
      ['Climate Intelligence Report'],
      [`Export Date: ${format(new Date(), 'MMM d, yyyy HH:mm')}`],
      [`Scenario: ${scenarios[selectedScenario].name}`],
      [`Scope Filter: ${selectedScope.toUpperCase()}`],
      [''],
      ['Current Emissions'],
      ['Scope', 'tCO₂e'],
      ['Scope 1', (exportData as any).currentEmissions.scope1],
      ['Scope 2', (exportData as any).currentEmissions.scope2],
      ['Scope 3', (exportData as any).currentEmissions.scope3],
      ['Total', (exportData as any).currentEmissions.total],
      [''],
      ['Milestones'],
      ['Year', 'Event', 'Status'],
      ...((exportData as any).milestones || []).map((m: any) => [m.year, m.event, m.status]),
    ];

    const csv = rows.map(row => Array.isArray(row) ? row.join(',') : row).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `climate-report-${selectedScenario}-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report exported as CSV');
  };

  const downloadMarkdown = () => {
    const md = `# Climate Intelligence Report

**Export Date:** ${format(new Date(), 'MMMM d, yyyy HH:mm')}
**Scenario:** ${scenarios[selectedScenario].name}
**Scope Filter:** ${selectedScope.toUpperCase()}
**Net Zero Target:** ${(exportData as any).netZeroProjectedYear}

## Current Emissions

| Scope | tCO₂e |
|-------|-------|
| Scope 1 | ${(exportData as any).currentEmissions.scope1.toLocaleString()} |
| Scope 2 | ${(exportData as any).currentEmissions.scope2.toLocaleString()} |
| Scope 3 | ${(exportData as any).currentEmissions.scope3.toLocaleString()} |
| **Total** | **${(exportData as any).currentEmissions.total.toLocaleString()}** |

## Quality Score
**${(exportData as any).qualityScore}/100** - High Quality

## Standards Compliance
${((exportData as any).standardsCompliance || []).map((s: any) => `- ${s.standard}: ${s.status}`).join('\n')}

## Key Insights
${((exportData as any).insights || []).map((i: any) => `- ${i.message}`).join('\n')}

## Upcoming Milestones
${((exportData as any).milestones || []).map((m: any) => `- **${m.year}**: ${m.event} (${m.status})`).join('\n')}

---
*Generated by FarmlyCarbon Climate Intelligence Platform*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `climate-report-${selectedScenario}-${format(new Date(), 'yyyy-MM-dd')}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report exported as Markdown');
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="h-4 w-4" />
          Smart Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuLabel className="flex items-center gap-2">
          <Check className="h-3 w-3 text-green-500" />
          Includes current filters & scenario
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={downloadJSON} className="cursor-pointer">
          <FileJson className="h-4 w-4 mr-2" />
          Export as JSON
        </DropdownMenuItem>
        <DropdownMenuItem onClick={downloadCSV} className="cursor-pointer">
          <FileSpreadsheet className="h-4 w-4 mr-2" />
          Export as CSV
        </DropdownMenuItem>
        <DropdownMenuItem onClick={downloadMarkdown} className="cursor-pointer">
          <FileText className="h-4 w-4 mr-2" />
          Export as Markdown
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
